name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DraftEmpire/
            git pull origin main

            # Backend setup
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt

            # Frontend setup
            cd ../frontend
            npm install
            npm run build

            # Deploy frontend
            sudo cp -r dist/* /var/www/html/

            # Restart Apache to apply changes
            sudo systemctl restart apache2
